---
title: "BuildMapImages"
author: "Dan Murphy"
date: "August 11, 2016"
output: github_document
---

The goal of the maps shown below is to indicate how the  minimum travel time for a fire engine will change after construction of a new fire station.  

```{r, message=FALSE,warning=FALSE}
library(ggmap)
library(dplyr)
```

First, the minimum travel time is calculated under the existing scenario with three fire stations and then again after construction of the new fire station.  

```{r, eval=FALSE}

LocationsDF$SecondsFromMain <- as.numeric(levels(LocationsDF$SecondsFromMain))[LocationsDF$SecondsFromMain]
LocationsDF$SecondsFromSta2 <- as.numeric(levels(LocationsDF$SecondsFromSta2))[LocationsDF$SecondsFromSta2]
LocationsDF$SecondsFromSta3 <- as.numeric(levels(LocationsDF$SecondsFromSta3))[LocationsDF$SecondsFromSta3]
LocationsDF$SecondsFromSta4 <- as.numeric(levels(LocationsDF$SecondsFromSta4))[LocationsDF$SecondsFromSta4]

LocationsDF <- LocationsDF %>% rowwise() %>% mutate(MinTravelExistingFireStations= 
                                                    min(SecondsFromMain,SecondsFromSta2,SecondsFromSta3))
LocationsDF <- LocationsDF %>% rowwise() %>% mutate(MinTravelw4FireStations = 
                                                    min(SecondsFromMain,SecondsFromSta2,
                                                        SecondsFromSta3,SecondsFromSta4))
```

```{r, echo=FALSE}
load(file="StationFirstSig2Long.RData")

```

